# Heading should be sentence case

# Words that may be uppercased even if they are not the first word in the sentence.
# Can also specify a regex that is compatible with the [Rust regex crate](https://docs.rs/regex/latest/regex/).
may_uppercase = [
    "[A-Z0-9]{2,5}s?",
    "APIs",
    "Android",
    "Angular",
    "Apple",
    "Auth",
    "Auth0",
    "Auth0 Actions?",
    "Azure",
    "Azure Developers?",
    "BigQuery",
    "Bitbucket",
    "Boolean",
    "Broadcast",
    "CAPTCHA",
    "ChatGPT",
    "Chrome",
    "Chrome Developer Tools",
    "Cloudflare",
    "Code Exchange",
    "Colab",
    "Content Delivery Network",
    "Cron Jobs?",
    "DataDog",
    "Dart",
    "Dashboard",
    "Deno",
    "Discord",
    "Discord Developers?",
    "Django",
    "Docker",
    "Drizzle",
    "Edge Functions?",
    "Enterprise Plan",
    "Expo",
    "Facebook",
    "Facebook Developers?",
    "Figma",
    "Figma Developers?",
    "Firebase",
    "Firebase Authentication",
    "Firestore",
    "Flutter",
    "Free Plan",
    "Git",
    "GitHub",
    "GitHub Actions",
    "GitLab",
    "GoTrue",
    "Google",
    "Grafana",
    "GraphQL",
    "Heroku",
    "Homebrew",
    "Hooks?",
    "Hugging Face",
    "I",
    "IVFFlat",
    "IdP",
    "Inbucket",
    "IntelliJ",
    "Ionic Angular",
    "Ionic React",
    "Ionic Vue",
    "JavaScript",
    "JWTs",
    "Kakao",
    "Kakao Developers?",
    "Kakao Login",
    "Keycloak",
    "Kotlin",
    "Kotlin Multiplatform",
    "Kysely",
    "Large Language Models?",
    "LinkedIn",
    "LinkedIn Developers?",
    "Linux",
    "LlamaIndex",
    "Llamafile",
    "Logs Explorer",
    "Magic Link",
    "Mixpeek",
    "Mixpeek Embed",
    "MySQL",
    "Navigable Small World",
    "Next.js",
    "Node.js",
    "Notion",
    "Nuxt",
    "OAuth",
    "Okta",
    "Ollama",
    "OpenAI",
    "Open ID Connect",
    "OrbStack",
    "Phoenix",
    "Pro Plan",
    "Podman",
    "Poetry",
    "Postgres",
    "PostgreSQL",
    "PostgREST",
    "Presence",
    "Prometheus",
    "Python",
    "React",
    "React Native",
    "Reciprocal Ranked Fusion",
    "Redis",
    "RedwoodJS",
    "Remix",
    "Retrieval Plugin",
    "Roboflow Inference",
    "Row Level Security",
    "SendGrid",
    "Sentry",
    "Server-Side Auth",
    "Server-Side Rendering",
    "Single Sign-On",
    "Slack",
    "Slack Developers?",
    "SolidJS",
    "Spotify",
    "Spotify Developers?",
    "Sqitch",
    "Storage",
    "Supabase",
    "Supabase Marketplace",
    "Svelte",
    "SvelteKit",
    "Swift",
    "SwiftUI",
    "Team Plan",
    "Third-Party Auth",
    "TimescaleDB",
    "Transformers.js",
    "Twilio",
    "Twitch",
    "Twitch Developers?",
    "Twitter",
    "Twitter Developers?",
    "TypeScript",
    "Uppy",
    "Upstash",
    "URIs",
    "URLs",
    "Unsplash",
    "Xcode",
    "VSCode",
    "Vecs",
    "Vercel",
    "Vercel Marketplace",
    "Visual Studio Code",
    "Vue",
    "Web",
    "WebAssembly",
    "WebP",
    "WebStorm",
    "Windows",
    "WorkOS",
    "Wrappers",
    "Zoom",
    "Zoom Developers?",
]

# Words that may be lowercased even if they are the first word in the sentence.
# Can also specify a regex that is compatible with the [Rust regex crate](https://docs.rs/regex/latest/regex/).
may_lowercase = ["iOS", "pgAudit"]
